'use client';
import { useEffect } from "react";
import Layout from "@/components/layout";
import { Link } from "wouter";
import { ArrowRight, Calendar, Clock, User } from "lucide-react";
import { Button } from "@/components/ui/button";

interface BlogPost {
  slug: string;
  title: string;
  excerpt: string;
  author: string;
  date: string;
  readTime: string;
  category: string;
  metaTitle: string;
  metaDescription: string;
  content: string[];
}

export const blogPosts: Record<string, BlogPost> = {
  "how-to-write-bathroom-remodel-proposal": {
    slug: "how-to-write-bathroom-remodel-proposal",
    title: "How to Write a Bathroom Remodel Proposal That Wins Jobs",
    excerpt: "Learn the essential elements every bathroom remodeling proposal needs to close more deals and set proper client expectations.",
    author: "ScopeGen Team",
    date: "December 5, 2025",
    readTime: "6 min read",
    category: "Proposal Writing",
    metaTitle: "How to Write a Bathroom Remodel Proposal | Complete Guide",
    metaDescription: "Step-by-step guide to writing professional bathroom remodeling proposals. Includes scope of work examples, pricing tips, and templates.",
    content: [
      "A well-written bathroom remodel proposal is the difference between winning the job and losing to a competitor. Your proposal isn't just a price quote—it's your first impression of how professional and organized your company is.",
      "## What Every Bathroom Remodel Proposal Needs",
      "### 1. Clear Project Scope",
      "Start with a detailed description of the work. Don't assume the homeowner knows what's included. List everything: demolition, plumbing, electrical, tile work, fixtures, and finishing touches. Be specific about what IS and ISN'T included.",
      "### 2. Material Specifications",
      "Include the exact products you plan to use—brand names, model numbers, colors, and sizes. This prevents disputes later and shows you've done your homework. For example: 'American Standard Champion 4 toilet in white' is better than 'new toilet.'",
      "### 3. Itemized Pricing",
      "Break down costs so homeowners understand where their money goes. Include labor, materials, permits, and any allowances for fixtures they'll select. Transparency builds trust.",
      "### 4. Timeline and Milestones",
      "Set realistic expectations. A typical bathroom remodel takes 2-3 weeks. List key milestones: demolition, rough-in, tile installation, fixture installation, and final walkthrough.",
      "### 5. Payment Terms",
      "Clearly state your payment schedule. Most contractors use: 30% deposit, 30% at rough-in, 30% at tile completion, 10% at final walkthrough. Include accepted payment methods.",
      "### 6. Warranty Information",
      "Stand behind your work. Specify what you warrant (workmanship, materials) and for how long. This reduces client anxiety and shows confidence in your quality.",
      "### 7. Terms and Conditions",
      "Protect yourself and set expectations. Include change order process, work hours, client responsibilities (clear access, decisions by deadline), and cancellation policy.",
      "## Common Mistakes to Avoid",
      "- **Being too vague**: 'New tile in shower' doesn't tell them enough. Specify type, size, pattern, and grout color.",
      "- **Forgetting exclusions**: Be clear about what you DON'T include (moving furniture, mold remediation if found, etc.)",
      "- **No photos or visuals**: Include before photos and inspiration images when possible.",
      "- **Rushing the estimate**: Take time to measure accurately and price correctly. Underbidding leads to problems.",
      "## Speed Up Your Proposal Process",
      "Writing detailed proposals takes time—often 1-2 hours per job. That's time you could spend on billable work or with family.",
      "ScopeGen was built specifically to solve this problem. Our bathroom remodeling templates include all the professional language and scope details you need. Just enter the project specifics, and you'll have a polished proposal in minutes, not hours.",
      "## Ready to Create Better Proposals?",
      "Try ScopeGen free and see how easy professional proposals can be."
    ]
  },
  "contractor-pricing-guide-2025": {
    slug: "contractor-pricing-guide-2025",
    title: "Contractor Pricing Guide 2025: How to Price Your Services",
    excerpt: "Learn how to price your contracting services competitively while maintaining healthy profit margins in 2025.",
    author: "ScopeGen Team",
    date: "December 3, 2025",
    readTime: "8 min read",
    category: "Business Tips",
    metaTitle: "Contractor Pricing Guide 2025 | How to Price Your Services",
    metaDescription: "Complete 2025 guide to pricing contractor services. Learn markup strategies, hourly rates, and how to compete while staying profitable.",
    content: [
      "Pricing your contracting services correctly is one of the most critical decisions you'll make. Price too high and you lose bids. Price too low and you're working for nothing—or worse, losing money.",
      "## Understanding Your Costs",
      "Before setting any prices, you need to know exactly what it costs you to run your business. This includes:",
      "### Direct Costs",
      "- **Materials**: Everything that goes into the project",
      "- **Labor**: Your hourly rate and any subcontractors or employees",
      "- **Equipment**: Rentals or depreciation on owned equipment",
      "- **Permits and fees**: Building permits, dump fees, etc.",
      "### Overhead Costs",
      "- **Insurance**: Liability, workers comp, vehicle",
      "- **Vehicle expenses**: Fuel, maintenance, payments",
      "- **Tools and equipment**: Replacement and maintenance",
      "- **Office expenses**: Phone, software, accounting",
      "- **Marketing**: Website, ads, business cards",
      "- **Your salary**: Don't forget to pay yourself!",
      "## The Markup Formula",
      "A common mistake is confusing markup with margin. Here's the difference:",
      "- **Markup**: Percentage added to cost (Cost × 1.5 = 50% markup)",
      "- **Margin**: Percentage of final price that's profit (50% markup = 33% margin)",
      "Most successful contractors use a 1.5x to 2x markup on materials and charge $50-150/hour for labor depending on trade and location.",
      "## Pricing by Trade (2025 Averages)",
      "### Bathroom Remodeling",
      "- Basic update: $5,000-15,000",
      "- Mid-range remodel: $15,000-30,000",
      "- High-end remodel: $30,000-75,000+",
      "### Kitchen Remodeling",
      "- Cabinet refacing: $4,000-10,000",
      "- Mid-range remodel: $25,000-50,000",
      "- High-end remodel: $50,000-150,000+",
      "### Roofing",
      "- Asphalt shingle (per square): $350-600",
      "- Metal roofing (per square): $700-1,200",
      "- Flat roof (per square): $400-800",
      "### Painting",
      "- Interior (per sq ft): $2-6",
      "- Exterior (per sq ft): $1.50-4",
      "- Cabinet painting: $3,000-8,000",
      "## Competing on Value, Not Price",
      "The contractors who thrive aren't the cheapest—they're the ones who communicate the most value. Your proposal should clearly show:",
      "- Exactly what's included (detailed scope of work)",
      "- Quality of materials you use",
      "- Your experience and warranty",
      "- Why you're worth more than the lowball bid",
      "## Present Professional Proposals",
      "A polished, detailed proposal justifies higher prices. When a homeowner compares your comprehensive ScopeGen proposal to a handwritten estimate from your competitor, you've already won the trust battle.",
      "Try ScopeGen free to see how professional proposals help you win more jobs at better prices."
    ]
  },
  "scope-of-work-template-examples": {
    slug: "scope-of-work-template-examples",
    title: "Scope of Work Template Examples for Contractors",
    excerpt: "Free scope of work templates and examples for bathroom, kitchen, roofing, painting, and other contractor trades.",
    author: "ScopeGen Team",
    date: "December 1, 2025",
    readTime: "10 min read",
    category: "Templates",
    metaTitle: "Scope of Work Template Examples | Free Contractor Templates",
    metaDescription: "Free scope of work templates for contractors. Examples for bathroom remodeling, kitchen renovation, roofing, painting, and more trades.",
    content: [
      "A good scope of work (SOW) protects both you and your client. It clearly defines what work will be done, what materials will be used, and what's excluded. Here are examples for common contractor trades.",
      "## Bathroom Remodeling Scope of Work Example",
      "**Project: Full Bathroom Remodel**",
      "### Demolition",
      "- Remove existing vanity, toilet, and bathtub/shower",
      "- Remove existing flooring and wall tile",
      "- Dispose of all debris at licensed facility",
      "### Rough-In Work",
      "- Install new water supply lines as needed",
      "- Install new drain lines for tub and vanity",
      "- Rough-in electrical for vanity lights, fan, and GFCI outlet",
      "### Finish Work",
      "- Install cement board on shower walls",
      "- Tile shower walls with client-selected tile",
      "- Install shower pan and glass enclosure",
      "- Install new vanity and countertop",
      "- Install toilet and faucets",
      "- Paint walls with two coats",
      "### Exclusions",
      "- Mold remediation if discovered",
      "- Structural repairs",
      "- Work outside bathroom footprint",
      "---",
      "## Roofing Scope of Work Example",
      "**Project: Full Roof Replacement**",
      "### Preparation",
      "- Set up ground tarps and protect landscaping",
      "- Install temporary gutter guards",
      "### Tear-Off",
      "- Remove existing shingles and underlayment",
      "- Inspect decking and replace damaged sections (up to 2 sheets included)",
      "- Dispose of all materials at licensed facility",
      "### Installation",
      "- Install synthetic underlayment on entire roof",
      "- Install drip edge on eaves and rakes",
      "- Install GAF Timberline HDZ shingles (color: Charcoal)",
      "- Install step flashing at all wall intersections",
      "- Install new pipe boots on all plumbing vents",
      "- Install ridge cap shingles at all ridges",
      "### Cleanup",
      "- Magnetic sweep of property for nails",
      "- Remove all debris and materials",
      "---",
      "## Painting Scope of Work Example",
      "**Project: Interior Painting - Whole House**",
      "### Preparation",
      "- Move furniture to center of rooms and cover",
      "- Fill nail holes and minor drywall cracks",
      "- Sand rough areas",
      "- Tape off trim, windows, and fixtures",
      "### Painting",
      "- Apply one coat primer to new drywall areas",
      "- Apply two coats Sherwin-Williams SuperPaint (color per room schedule)",
      "- Paint all ceilings with flat white",
      "- Paint all trim with semi-gloss white",
      "### Cleanup",
      "- Remove all tape and plastic",
      "- Return furniture to original positions",
      "- Touch up as needed",
      "---",
      "## Generate Professional Scopes Instantly",
      "Writing detailed scopes of work takes time. ScopeGen has pre-built templates for 9 contractor trades with all the professional language you need. Enter your project details and get a complete scope in minutes.",
      "Try ScopeGen free and never write a scope from scratch again."
    ]
  },
  "win-more-contractor-bids": {
    slug: "win-more-contractor-bids",
    title: "5 Ways to Win More Contractor Bids (Without Lowering Your Price)",
    excerpt: "Learn proven strategies to win more contracting jobs without sacrificing your profit margins.",
    author: "ScopeGen Team",
    date: "November 28, 2025",
    readTime: "5 min read",
    category: "Business Tips",
    metaTitle: "How to Win More Contractor Bids | 5 Proven Strategies",
    metaDescription: "Win more contracting jobs without cutting prices. Learn 5 proven strategies successful contractors use to beat the competition.",
    content: [
      "Every contractor knows the frustration: you spend hours creating an estimate, only to lose the job to someone cheaper. But here's the truth—price isn't always why you lost.",
      "## 1. Respond Faster Than Anyone Else",
      "The first contractor to send a detailed proposal often wins. Homeowners are eager to move forward, and waiting days for quotes cools their enthusiasm. Aim to send proposals within 24 hours of the initial visit.",
      "## 2. Look More Professional",
      "A handwritten estimate on a piece of paper loses to a polished, typed proposal every time. Your proposal represents your company. If it looks thrown together, clients wonder if your work will be the same.",
      "Include your logo, contact information, and consistent formatting. Use clear headings and easy-to-read fonts.",
      "## 3. Be Specific About What's Included",
      "Vague estimates scare homeowners. They wonder what you're hiding or what will cost extra later. Instead, list everything in detail:",
      "- Exact materials and brands",
      "- Every step of the process",
      "- What IS and ISN'T included",
      "- Timeline expectations",
      "When clients can see exactly what they're paying for, higher prices feel justified.",
      "## 4. Address Their Concerns Before They Ask",
      "Smart proposals answer questions before clients have to ask:",
      "- How will you protect their home? (drop cloths, dust containment)",
      "- What's your warranty?",
      "- What happens if you find unexpected problems?",
      "- How do they pay and when?",
      "This builds trust and shows experience.",
      "## 5. Follow Up",
      "Many contractors send a proposal and wait. Following up (politely) shows you want the job and reminds clients to make a decision. A simple call or email 2-3 days after sending the proposal can make the difference.",
      "## Make Professional Proposals Easy",
      "The common thread in all these tips? Your proposal matters more than you think. That's why we built ScopeGen—to help contractors create professional, detailed proposals in minutes instead of hours.",
      "Try ScopeGen free and see how winning proposals can be your competitive advantage."
    ]
  },
  "bathroom-remodeling-proposal": {
    slug: "bathroom-remodeling-proposal",
    title: "How to Write a Bathroom Remodeling Proposal in 10 Minutes",
    excerpt: "Learn how to create a professional bathroom remodeling proposal quickly with our step-by-step guide and ready-to-use scope of work template.",
    author: "ScopeGen Team",
    date: "December 10, 2025",
    readTime: "8 min read",
    category: "Proposal Writing",
    metaTitle: "How to Write a Bathroom Remodeling Proposal in 10 Minutes | ScopeGen",
    metaDescription: "Step-by-step guide to writing a bathroom remodeling proposal. Includes sample scope of work, pricing tips, and a template you can use today.",
    content: [
      "Writing a bathroom remodeling proposal doesn't have to take hours. With the right structure and a clear scope of work, you can create professional proposals in just 10 minutes. This guide shows you exactly how.",
      "## Why Proposals Matter for Bathroom Remodelers",
      "Your proposal is often the deciding factor between winning and losing a job. Homeowners typically get 3-5 quotes for bathroom remodeling projects, and the contractor with the most professional, detailed proposal wins—even if they're not the cheapest.",
      "A well-written bathroom remodeling proposal:",
      "- Builds trust before you even start the work",
      "- Sets clear expectations to avoid disputes later",
      "- Protects you legally with documented scope and terms",
      "- Justifies your pricing with detailed breakdowns",
      "- Shows homeowners exactly what they're paying for",
      "Studies show that contractors who provide detailed proposals have a 40% higher close rate than those who provide simple quotes. Your proposal is your first demonstration of professionalism.",
      "## What to Include in Every Bathroom Proposal",
      "Every bathroom remodeling proposal needs these essential sections:",
      "### Project Overview",
      "Start with a brief description of the project. Summarize what the homeowner wants and what you'll deliver. This shows you listened during the consultation.",
      "### Detailed Scope of Work",
      "This is the heart of your proposal. List every task you'll perform, from demolition to final cleanup. Be specific—vague scopes lead to disputes.",
      "### Materials and Specifications",
      "List every product you'll install with brand names, model numbers, and colors. This prevents the 'that's not what I expected' conversation later.",
      "### Timeline and Milestones",
      "Give homeowners a realistic timeline with key milestones: demolition, rough-in, tile work, fixture installation, and final walkthrough.",
      "### Pricing Breakdown",
      "Break down costs into categories: labor, materials, permits, and contingency. Transparency builds trust and justifies your price.",
      "### Payment Schedule",
      "Specify when payments are due: typically 30% deposit, 30% at rough-in, 30% at tile completion, and 10% at final walkthrough.",
      "### Terms and Conditions",
      "Include change order process, work hours, warranty information, and cancellation policy.",
      "## Step-by-Step Guide to Writing Your Proposal",
      "### Step 1: Start with the Consultation Notes (2 minutes)",
      "Review your notes from the site visit. Note the bathroom size, current condition, and exactly what the homeowner wants. This becomes your project overview.",
      "### Step 2: Build Your Scope of Work (4 minutes)",
      "List every task from start to finish. Use action verbs: Remove, Install, Tile, Paint. Include quantities and specifications.",
      "### Step 3: Add Materials List (2 minutes)",
      "List each product with brand, model, color, and quantity. If the homeowner will select items, list allowances instead.",
      "### Step 4: Calculate Pricing (1 minute)",
      "Add up material costs, labor hours, permits, and your markup. Break it down by category.",
      "### Step 5: Final Review (1 minute)",
      "Check for completeness. Make sure exclusions are clear. Verify all numbers add up.",
      "## Sample Bathroom Scope of Work",
      "Use this template as a starting point for your bathroom remodeling proposals:",
      "**Project: Full Bathroom Remodel (5x8 master bathroom)**",
      "### Phase 1: Demolition",
      "- Remove existing vanity, toilet, and tub/shower surround",
      "- Remove existing floor tile down to subfloor",
      "- Remove existing wall tile in tub/shower area",
      "- Disconnect and cap existing plumbing fixtures",
      "- Dispose of all demolition debris at licensed facility",
      "### Phase 2: Rough Plumbing & Electrical",
      "- Install new PEX water supply lines to shower valve location",
      "- Install new ABS drain for shower (2-inch)",
      "- Relocate water supply for vanity (if needed)",
      "- Install new vent fan wiring and bathroom circuit",
      "- Install GFCI outlets at vanity location",
      "- Install recessed light wiring (quantity: 4)",
      "### Phase 3: Subfloor & Waterproofing",
      "- Install 1/2-inch cement board on floor",
      "- Install cement board on shower walls",
      "- Apply RedGard waterproofing membrane to shower area",
      "- Allow 24-hour cure time",
      "### Phase 4: Tile Installation",
      "- Install porcelain floor tile (12x24, client selection)",
      "- Install ceramic wall tile in shower (subway style, 3x6)",
      "- Install mosaic accent tile on shower floor",
      "- Grout all tile with sanded grout (color: Delorean Gray)",
      "- Seal grout lines",
      "### Phase 5: Fixture Installation",
      "- Install new Kohler toilet (Wellworth, white)",
      "- Install 36-inch vanity with quartz countertop",
      "- Install undermount sink and Delta faucet (Arvo series)",
      "- Install frameless glass shower door (48-inch)",
      "- Install Moen shower valve and trim kit (Genta LX series)",
      "- Install rain showerhead and handheld sprayer",
      "### Phase 6: Finishing",
      "- Install bathroom mirror (36x48 framed)",
      "- Install vanity lighting fixture (3-light bar)",
      "- Install Panasonic exhaust fan (110 CFM)",
      "- Install towel bars and accessories",
      "- Paint walls and ceiling (2 coats, Sherwin-Williams)",
      "- Caulk all edges and transitions",
      "- Final cleanup and walkthrough",
      "### Exclusions",
      "- Mold remediation (if discovered, quoted separately)",
      "- Structural repairs to subfloor or framing",
      "- Replacement of main stack or sewer line",
      "- Work outside the bathroom footprint",
      "- Permits (included in price)",
      "## Common Mistakes to Avoid",
      "Even experienced contractors make these proposal mistakes:",
      "### Being Too Vague",
      "'New tile' isn't enough. Specify the type (porcelain, ceramic), size (12x24), pattern (staggered brick), and grout color. Vague scopes lead to 'I thought that was included' arguments.",
      "### Forgetting Exclusions",
      "Always list what you DON'T include. This protects you when hidden problems appear: mold behind walls, rotted subfloors, outdated plumbing that needs replacement.",
      "### Underpricing to Win the Job",
      "Low prices attract low-quality clients and leave you working for nothing. Price fairly and compete on value, not just cost.",
      "### Skipping the Timeline",
      "Homeowners need to know how long they'll be without a bathroom. Be realistic—a typical full remodel takes 2-3 weeks minimum.",
      "### No Change Order Process",
      "Clearly state that any changes require a written change order with adjusted price and timeline. This prevents scope creep.",
      "### Missing Warranty Information",
      "State exactly what you warranty and for how long. Typically: 1-2 years on workmanship, manufacturer warranty on products.",
      "## Speed Up Your Proposal Process",
      "Writing detailed proposals from scratch takes 1-2 hours per job. That's time you could spend on billable work or with your family.",
      "ScopeGen was built to solve this exact problem. Our bathroom remodeling templates include professional language, complete scope details, and proper formatting. Just enter the project specifics and you'll have a polished proposal ready to send.",
      "## Ready to Create Better Proposals?",
      "Use this template inside ScopeGen with one click. Create professional bathroom remodeling proposals in minutes, not hours."
    ]
  },
  "roofing-proposal-checklist": {
    slug: "roofing-proposal-checklist",
    title: "Roofing Proposal Checklist: What to Include So You Get Paid",
    excerpt: "Complete checklist for roofing proposals that protect your business and ensure you get paid. Includes materials breakdown, warranty terms, and sample scope of work.",
    author: "ScopeGen Team",
    date: "December 9, 2025",
    readTime: "9 min read",
    category: "Proposal Writing",
    metaTitle: "Roofing Proposal Checklist: What to Include So You Get Paid | ScopeGen",
    metaDescription: "Complete roofing proposal checklist with materials breakdown, warranty terms, payment schedule, and sample proposal. Never miss important details again.",
    content: [
      "A complete roofing proposal protects your business and ensures you get paid. Missing key details can lead to disputes, unpaid invoices, and damaged relationships. This checklist covers everything your roofing proposal needs.",
      "## Essential Sections Every Roofing Proposal Needs",
      "Your roofing proposal is a legal document. It protects both you and the homeowner by clearly defining what's included, what's not, and how payment works.",
      "### 1. Company Information",
      "- Your company name, address, phone, and email",
      "- License number and insurance information",
      "- Your logo for professional branding",
      "### 2. Client Information",
      "- Homeowner name and address",
      "- Property address (if different)",
      "- Contact phone and email",
      "### 3. Project Description",
      "- Roof type (asphalt shingle, metal, flat, tile)",
      "- Total square footage",
      "- Number of layers to remove",
      "- Special features (skylights, chimneys, dormers)",
      "### 4. Detailed Scope of Work",
      "- Every step from setup to final cleanup",
      "- Quantities and measurements",
      "- Specific materials to be used",
      "### 5. Materials Breakdown",
      "- Shingles/roofing material (brand, color, warranty)",
      "- Underlayment type",
      "- Flashing materials",
      "- Ventilation components",
      "- Drip edge specifications",
      "### 6. Pricing",
      "- Itemized costs (labor, materials, permits)",
      "- Total project cost",
      "- Any potential additional costs",
      "### 7. Timeline",
      "- Start date",
      "- Estimated completion",
      "- Weather contingency language",
      "### 8. Payment Terms",
      "- Deposit amount and due date",
      "- Progress payments (if any)",
      "- Final payment timing",
      "- Accepted payment methods",
      "### 9. Warranty Information",
      "- Workmanship warranty (your guarantee)",
      "- Manufacturer warranty details",
      "- What voids the warranty",
      "### 10. Terms and Conditions",
      "- Change order process",
      "- Cancellation policy",
      "- Damage limitations",
      "- Dispute resolution",
      "## Materials Breakdown: What to Specify",
      "Vague material descriptions lead to disputes. Be specific about every component:",
      "### Shingles",
      "- Brand: GAF, Owens Corning, CertainTeed, etc.",
      "- Product line: GAF Timberline HDZ, OC Duration, etc.",
      "- Color: Use manufacturer color names",
      "- Warranty level: 25-year, 30-year, Lifetime",
      "Example: 'GAF Timberline HDZ Architectural Shingles, color: Charcoal, Lifetime Limited Warranty'",
      "### Underlayment",
      "- Type: Synthetic or felt",
      "- Weight/quality: 15lb, 30lb, or premium synthetic",
      "- Ice and water shield locations",
      "Example: 'GAF FeltBuster Synthetic Underlayment on entire roof surface, GAF WeatherWatch Ice & Water Shield in valleys and at eaves (6 feet up from edge)'",
      "### Flashing",
      "- Material: Aluminum, galvanized steel, copper",
      "- Locations: Valleys, walls, chimneys, vents",
      "Example: 'Aluminum step flashing at all wall intersections, new aluminum drip edge on all eaves and rakes'",
      "### Ventilation",
      "- Ridge vent type and linear feet",
      "- Soffit vent requirements",
      "- Any power vents or static vents",
      "Example: 'Install 35 linear feet GAF Cobra SnowCountry Ridge Vent, ensure adequate soffit ventilation for proper airflow'",
      "## Warranty Terms: Protect Yourself and Your Customer",
      "Warranties are critical for roofing projects. Be clear about what's covered:",
      "### Your Workmanship Warranty",
      "State exactly what you guarantee and for how long:",
      "- 'ABC Roofing warrants all workmanship for a period of 5 years from the date of substantial completion'",
      "- 'This warranty covers defects in installation, including improper nailing, flashing, and sealing'",
      "- 'This warranty does not cover damage caused by storms, falling objects, or owner modifications'",
      "### Manufacturer Warranty",
      "Explain the shingle warranty clearly:",
      "- 'GAF Timberline HDZ shingles include a Lifetime Limited Warranty from GAF'",
      "- 'Full warranty details available at manufacturer's website'",
      "- 'Warranty requires proper installation by GAF Certified Contractor'",
      "### What Voids Warranties",
      "List activities that void coverage:",
      "- Walking on roof unnecessarily",
      "- Installing satellite dishes without proper techniques",
      "- Pressure washing shingles",
      "- Failing to maintain gutters and ventilation",
      "## Payment Schedule: Ensure You Get Paid",
      "The payment schedule protects your cash flow and reduces risk. Here's a typical structure for roofing projects:",
      "### Option 1: Standard Three-Payment Schedule",
      "- 33% deposit upon signing contract",
      "- 33% at material delivery",
      "- 34% upon completion and final inspection",
      "### Option 2: Insurance Claim Jobs",
      "- Homeowner deposit (deductible amount) upon signing",
      "- Remaining balance due upon completion (paid by insurance)",
      "- Supplements invoiced separately when approved",
      "### Option 3: Large Commercial Projects",
      "- 25% deposit",
      "- 25% at 50% completion",
      "- 25% at 90% completion",
      "- 25% at final inspection and punch list completion",
      "### Payment Terms to Include",
      "- 'Payment due within 7 days of invoice date'",
      "- 'Late payments subject to 1.5% monthly interest'",
      "- 'Work may be suspended for overdue payments'",
      "- 'Accepted methods: Check, credit card, bank transfer'",
      "## Sample Roofing Proposal Scope of Work",
      "Use this as a template for your roofing proposals:",
      "**Project: Complete Roof Replacement**",
      "**Property: 2,400 sq ft single-story home**",
      "### Preparation and Protection",
      "- Place tarps to protect landscaping, driveway, and pool area",
      "- Set up dump trailer and portable toilet for crew",
      "- Install magnetic ground covers to catch nails",
      "- Protect all AC units and outdoor equipment",
      "### Tear-Off",
      "- Remove existing asphalt shingles (2 layers)",
      "- Remove existing underlayment down to decking",
      "- Inspect all decking for damage or rot",
      "- Replace damaged plywood decking (up to 2 sheets included, additional sheets $85 each)",
      "- Remove and dispose of all debris at licensed facility",
      "### Flashing and Edge Metal",
      "- Install new aluminum drip edge on all eaves (white)",
      "- Install new aluminum drip edge on all rakes (white)",
      "- Install aluminum step flashing at all wall intersections",
      "- Install new pipe boots on all plumbing vents (8 total)",
      "- Flash around skylight with new flashing kit",
      "- Install chimney flashing with aluminum step and counter flashing",
      "### Underlayment and Ice Shield",
      "- Install GAF FeltBuster synthetic underlayment on entire roof",
      "- Install GAF WeatherWatch ice and water shield at all eaves (6 ft minimum)",
      "- Install ice and water shield in all valleys",
      "- Install ice and water shield around skylights and chimney",
      "### Shingle Installation",
      "- Install GAF Timberline HDZ shingles (Color: Charcoal)",
      "- Install shingles per GAF specifications with 6 nails per shingle",
      "- Install GAF TimberTex hip and ridge cap shingles",
      "- Install GAF Cobra SnowCountry ridge vent (40 linear feet)",
      "- Install GAF starter strip at all eaves and rakes",
      "### Cleanup and Final Inspection",
      "- Magnetic sweep entire property (minimum 3 passes)",
      "- Remove all debris and materials from property",
      "- Final roof inspection for proper installation",
      "- Provide homeowner with warranty documentation",
      "- Register warranty with GAF",
      "### Exclusions",
      "- Gutter replacement or repair (can quote separately)",
      "- Soffit or fascia repairs (can quote separately)",
      "- Interior repairs from prior leaks",
      "- Tree trimming (recommend 10 ft clearance)",
      "- Additional decking beyond 2 sheets (charged at $85/sheet)",
      "**Total Investment: $12,500**",
      "**Includes:** All labor, materials, permits, debris removal, and GAF Lifetime Limited Warranty",
      "## Create Professional Roofing Proposals in 60 Seconds",
      "Stop writing roofing proposals from scratch. ScopeGen has ready-to-use roofing templates with professional language, complete scope details, and proper legal terms.",
      "Just enter your project measurements, select the shingle type and color, and you'll have a complete proposal ready to present to your customer.",
      "Create a professional roofing proposal in 60 seconds with ScopeGen."
    ]
  },
  "kitchen-remodel-scope-of-work": {
    slug: "kitchen-remodel-scope-of-work",
    title: "Kitchen Remodel Scope of Work: Simple Template for Contractors",
    excerpt: "Free kitchen remodel scope of work template for contractors. Includes cabinet specifications, appliance allowances, and a complete sample you can use today.",
    author: "ScopeGen Team",
    date: "December 8, 2025",
    readTime: "10 min read",
    category: "Templates",
    metaTitle: "Kitchen Remodel Scope of Work: Simple Template for Contractors | ScopeGen",
    metaDescription: "Free kitchen remodel scope of work template with cabinet specs, appliance allowances, and sample scope. Perfect for contractors who want professional proposals.",
    content: [
      "A detailed kitchen remodel scope of work protects you from disputes and ensures everyone knows exactly what's included. This guide includes everything you need to write professional kitchen scopes, plus a complete template you can use today.",
      "## Understanding Scope of Work for Kitchen Remodels",
      "The scope of work (SOW) is the backbone of your kitchen remodeling proposal. It defines every task you'll perform, every material you'll install, and every item that's excluded from your price.",
      "### Why a Detailed Scope Matters",
      "Kitchen remodels are complex projects with many moving parts. Without a detailed scope:",
      "- Homeowners assume things are included that aren't",
      "- You end up doing work you didn't price for",
      "- Disputes arise about what was agreed upon",
      "- Final payment gets held up over misunderstandings",
      "A comprehensive kitchen scope of work:",
      "- Documents every aspect of the project in writing",
      "- Sets clear expectations from day one",
      "- Provides a reference point for change orders",
      "- Protects you legally if disputes arise",
      "### Components of a Kitchen Scope",
      "Every kitchen remodel scope should include these sections:",
      "- Demolition and preparation",
      "- Rough plumbing and electrical",
      "- Cabinet installation",
      "- Countertop installation",
      "- Appliance installation",
      "- Backsplash and finishes",
      "- Final details and cleanup",
      "- Clear exclusions",
      "## Kitchen-Specific Items to Include",
      "Kitchen remodels have unique requirements that other projects don't. Make sure your scope addresses these kitchen-specific items:",
      "### Electrical Requirements",
      "Modern kitchens need significant electrical work:",
      "- Dedicated 20-amp circuits for small appliances",
      "- 50-amp circuit for electric range",
      "- 20-amp circuit for dishwasher",
      "- 20-amp circuit for garbage disposal",
      "- Under-cabinet lighting circuits",
      "- Pendant light locations",
      "- GFCI outlet placement (required within 6 feet of sink)",
      "### Plumbing Considerations",
      "- Water supply lines for sink and dishwasher",
      "- Drain connections and venting",
      "- Gas line for range (if applicable)",
      "- Ice maker water line (if applicable)",
      "- Pot filler installation (if requested)",
      "- Garbage disposal connection",
      "### Ventilation",
      "- Range hood venting (ducted vs. recirculating)",
      "- Duct run location and length",
      "- Exterior vent cap installation",
      "- CFM requirements based on range size",
      "## Cabinet Specifications: Get It Right",
      "Cabinets are typically the largest expense in a kitchen remodel. Your scope must be specific about cabinet details:",
      "### Cabinet Type",
      "Specify the construction quality level:",
      "- Stock cabinets: Pre-made standard sizes, limited options",
      "- Semi-custom cabinets: Standard boxes with custom options",
      "- Custom cabinets: Built to exact specifications",
      "### Material and Construction",
      "- Box material: Plywood vs. particle board",
      "- Face frame vs. frameless (European) style",
      "- Door style: Shaker, raised panel, flat panel, etc.",
      "- Door material: Solid wood, MDF, thermofoil",
      "- Finish type: Paint, stain, or natural",
      "### Hardware",
      "- Drawer slides: Soft-close, full extension",
      "- Hinges: Concealed, soft-close",
      "- Pulls and knobs: Style, size, finish",
      "- Lazy susans, pull-out organizers, etc.",
      "### Specific Cabinet List",
      "Include a complete cabinet schedule:",
      "- Base cabinets: Quantity, size, location",
      "- Wall cabinets: Quantity, size, height",
      "- Specialty cabinets: Corner, pantry, appliance",
      "- Fillers and trim pieces",
      "Example: 'Install (4) 36-inch base cabinets, (2) 24-inch base cabinets, (1) 36-inch sink base, (8) 30-inch wall cabinets, (2) 42-inch wall cabinets, crown molding on all wall cabinets'",
      "## Appliance Allowances: Avoid Surprises",
      "Appliances can make or break a kitchen remodel budget. Handle them clearly in your scope:",
      "### Option 1: Allowance System",
      "Set a budget allowance for appliances the homeowner will select:",
      "- 'Appliance allowance: $8,000'",
      "- 'Includes: Range, refrigerator, dishwasher, microwave'",
      "- 'Homeowner selects appliances within allowance'",
      "- 'Costs above allowance are additional'",
      "### Option 2: Specified Appliances",
      "List exact appliances if already selected:",
      "- GE Profile 30-inch gas range (Model PGB960)",
      "- Samsung 27 cu ft French door refrigerator (Model RF27T5201SR)",
      "- Bosch 500 series dishwasher (Model SHPM65Z55N)",
      "### Option 3: Installation Only",
      "If the homeowner supplies appliances:",
      "- 'Install homeowner-provided appliances'",
      "- 'Appliances must be on-site before installation date'",
      "- 'Contractor not responsible for appliance defects'",
      "- 'Additional charge for appliance delivery/returns if not on-site'",
      "### What Appliance Installation Includes",
      "Be specific about installation scope:",
      "- Uncrating and positioning",
      "- Connecting water, gas, and electrical",
      "- Testing for proper operation",
      "- Removing packaging materials",
      "- NOT included: Extended warranties, owner orientation",
      "## Sample Kitchen Scope of Work Template",
      "Use this comprehensive template for your kitchen remodeling proposals:",
      "**Project: Complete Kitchen Remodel**",
      "**Size: 12x15 (180 sq ft) U-shaped kitchen**",
      "### Phase 1: Pre-Construction",
      "- Obtain all required building permits",
      "- Order cabinets and countertops (lead time: 4-6 weeks)",
      "- Finalize all material selections with homeowner",
      "- Schedule subcontractors (plumber, electrician)",
      "### Phase 2: Demolition",
      "- Protect adjacent rooms with plastic sheeting and floor covering",
      "- Remove existing cabinets, countertops, and backsplash",
      "- Remove existing flooring (vinyl sheet)",
      "- Disconnect and remove existing appliances",
      "- Remove existing sink and faucet",
      "- Remove existing lighting fixtures",
      "- Dispose of all debris at licensed facility",
      "### Phase 3: Rough-In Work",
      "- Relocate water supply lines for new sink location",
      "- Install new gas line for range (10 feet)",
      "- Install dedicated electrical circuits:",
      "- (2) 20-amp small appliance circuits",
      "- (1) 50-amp range circuit",
      "- (1) 20-amp dishwasher circuit",
      "- (1) 20-amp disposal circuit",
      "- (1) 15-amp refrigerator circuit",
      "- Install electrical boxes for under-cabinet and pendant lighting",
      "- Run ductwork for range hood (6-inch duct, 15 feet to exterior)",
      "- Install exterior vent cap",
      "- Repair drywall as needed after rough-in",
      "### Phase 4: Flooring",
      "- Install 1/4-inch plywood underlayment",
      "- Install luxury vinyl plank flooring (Shaw Classico, color: Molo)",
      "- Install shoe molding at perimeter",
      "- Flooring under cabinets: Yes (full coverage)",
      "### Phase 5: Cabinet Installation",
      "- Install KraftMaid wall cabinets (14 total per cabinet schedule)",
      "- Install KraftMaid base cabinets (10 total per cabinet schedule)",
      "- Install 42-inch tall pantry cabinet",
      "- Level and secure all cabinets",
      "- Install cabinet crown molding",
      "- Install all cabinet hardware (Amerock pulls, satin nickel)",
      "- Adjust doors and drawers for proper alignment",
      "### Phase 6: Countertops",
      "- Template countertops after cabinets installed",
      "- Fabricate and install quartz countertops (Caesarstone Calacatta Nuvo)",
      "- Include 4-inch backsplash piece behind range",
      "- Cut sink opening (undermount)",
      "- Polish and seal all edges",
      "- Total surface area: Approximately 45 square feet",
      "### Phase 7: Backsplash",
      "- Install ceramic subway tile backsplash (3x6, white)",
      "- Install from countertop to bottom of wall cabinets",
      "- Include outlet covers to match",
      "- Grout with unsanded grout (color: white)",
      "- Seal grout lines",
      "### Phase 8: Appliance Installation",
      "- Install gas range and connect gas line",
      "- Install range hood and connect to ductwork",
      "- Install refrigerator and connect water line",
      "- Install dishwasher and connect water/drain/electric",
      "- Install garbage disposal and air switch",
      "- Install built-in microwave",
      "- Test all appliances for proper operation",
      "### Phase 9: Plumbing Fixtures",
      "- Install undermount sink (Kohler Riverby, white)",
      "- Install kitchen faucet (Moen Arbor, spot resist stainless)",
      "- Install soap dispenser",
      "- Connect dishwasher drain and supply",
      "- Test for leaks",
      "### Phase 10: Electrical Fixtures",
      "- Install under-cabinet LED lighting (4 fixtures)",
      "- Install pendant lights over island (3 fixtures)",
      "- Install recessed lights (6 fixtures)",
      "- Install dimmer switches for main lighting",
      "- Install new GFCI outlets at countertop locations (6 outlets)",
      "### Phase 11: Final Details",
      "- Paint walls with two coats (Sherwin-Williams, color TBD)",
      "- Touch up all paint and caulk",
      "- Install outlet and switch covers",
      "- Final adjustment of all cabinet doors and drawers",
      "- Clean all surfaces and appliances",
      "- Final walkthrough with homeowner",
      "- Obtain final inspection approval",
      "### Exclusions",
      "- Structural modifications (wall removal, load-bearing changes)",
      "- Refinishing hardwood floors in adjacent rooms",
      "- Painting rooms beyond kitchen",
      "- Moving gas meter or main electrical panel",
      "- Asbestos or lead paint remediation (if discovered)",
      "- Window or door replacement",
      "- HVAC modifications",
      "### Allowances Included",
      "- Appliance allowance: $6,000",
      "- Lighting fixture allowance: $1,200",
      "- Cabinet hardware allowance: $400",
      "- Faucet and sink allowance: $800",
      "Selections above allowances will be invoiced at cost plus 15%.",
      "**Total Project Investment: $65,000**",
      "**Timeline: 6-8 weeks from permit approval**",
      "## Generate Your Kitchen Proposal Automatically",
      "Stop spending hours writing kitchen remodel proposals. ScopeGen has comprehensive kitchen templates with all the professional language, detailed scope sections, and proper legal terms.",
      "Just enter your project details—cabinet count, countertop material, appliances—and get a complete, professional proposal ready to present to your client.",
      "Generate your kitchen proposal automatically with ScopeGen."
    ]
  },
  "bathroom-proposal-without-copy-paste": {
    slug: "bathroom-proposal-without-copy-paste",
    title: "How to Write a Bathroom Remodeling Proposal (Without Copy-Paste)",
    excerpt: "Stop copying and pasting from old proposals. Learn how to create custom bathroom remodeling proposals that win jobs and protect your profit.",
    author: "ScopeGen Team",
    date: "December 11, 2025",
    readTime: "6 min read",
    category: "Proposal Writing",
    metaTitle: "How to Write a Bathroom Remodeling Proposal Without Copy-Paste | ScopeGen",
    metaDescription: "Learn how to write custom contractor proposals for bathroom remodels without copying from old documents. Generate professional proposals in 60 seconds.",
    content: [
      "We've all done it—copied last month's bathroom proposal, changed the name and address, and hoped we didn't miss anything. But copy-paste proposals are risky. Old pricing, wrong materials, and outdated language can cost you the job or eat your profit.",
      "## The Copy-Paste Problem",
      "Every bathroom remodel is different. When you copy from an old contractor proposal, you're gambling that:",
      "- Material prices haven't changed (spoiler: they always do)",
      "- The scope matches the new project (it rarely does)",
      "- You didn't leave the old client's name somewhere embarrassing",
      "- The exclusions still make sense for this job",
      "One wrong number can cost you thousands. One missed exclusion can turn a profitable job into a nightmare.",
      "## A Better Way to Write Contractor Proposals",
      "Instead of copying old proposals, you need a system that:",
      "- Generates fresh scope of work for each project",
      "- Uses current material pricing",
      "- Includes the right exclusions automatically",
      "- Looks professional every time",
      "### Start with a Template, Not an Old Proposal",
      "A good contractor proposal template is different from an old proposal. Templates give you the structure and professional language, but you fill in project-specific details fresh each time.",
      "Your bathroom remodeling proposal template should include:",
      "- **Scope sections**: Demolition, rough-in, tile, fixtures, finishes",
      "- **Standard exclusions**: Mold, structural issues, work outside footprint",
      "- **Payment terms**: Industry-standard milestone payments",
      "- **Warranty language**: What you guarantee and for how long",
      "### Customize the Details, Not the Structure",
      "Once you have a solid template, you only need to customize:",
      "- Client name and address",
      "- Specific fixtures and finishes",
      "- Square footage and quantities",
      "- Project-specific exclusions",
      "- Current pricing",
      "This takes minutes, not hours—and you never accidentally leave 'Mr. Johnson' in a proposal for Mrs. Smith.",
      "## What Every Bathroom Contractor Proposal Needs",
      "Whether you use a template or build from scratch, every bathroom remodeling proposal needs these elements:",
      "### Detailed Scope of Work",
      "List every task with specific details. 'Install new tile' isn't enough. Say 'Install 12x24 porcelain tile on shower walls in running bond pattern with Mapei Keracolor U grout (color: Silver).'",
      "### Material Specifications",
      "Name brands, model numbers, colors, and quantities. This prevents 'I thought it was going to be...' conversations later.",
      "### Clear Exclusions",
      "What you DON'T include is as important as what you do. Always exclude mold remediation, structural repairs, and work outside the bathroom footprint.",
      "### Payment Schedule",
      "Break payments into milestones: deposit, rough-in, tile completion, final walkthrough. This protects your cash flow and reduces risk.",
      "### Warranty Terms",
      "State exactly what you guarantee. Typically 1-2 years on workmanship, with manufacturer warranties on fixtures and materials.",
      "## The 60-Second Contractor Proposal",
      "You don't have to choose between copy-paste and writing from scratch. Modern contractor proposal software lets you generate custom proposals in about a minute.",
      "With [ScopeGen](/), you:",
      "- Select the project type (full remodel, tub-to-shower, etc.)",
      "- Enter client info and project details",
      "- Choose fixtures and finish levels",
      "- Get a complete, professional proposal instantly",
      "No copying. No pasting. No embarrassing mistakes.",
      "## Ready to Stop Copy-Pasting?",
      "Your contractor proposals deserve better than Frankenstein documents stitched together from old jobs. Generate your next proposal in 60 seconds with [ScopeGen](/)."
    ]
  },
  "roofing-proposal-checklist-storm-jobs": {
    slug: "roofing-proposal-checklist-storm-jobs",
    title: "Roofing Proposal Checklist for Storm Damage Jobs",
    excerpt: "Complete checklist for storm damage roofing proposals. Includes insurance documentation, supplement language, and how to protect your payment.",
    author: "ScopeGen Team",
    date: "December 11, 2025",
    readTime: "7 min read",
    category: "Proposal Writing",
    metaTitle: "Roofing Proposal Checklist for Storm Damage Jobs | ScopeGen",
    metaDescription: "Complete checklist for storm damage roofing proposals. Learn what to include for insurance claims, supplement documentation, and payment protection.",
    content: [
      "Storm damage roofing jobs are different from regular replacements. Insurance is involved, timelines are compressed, and documentation matters more than ever. This contractor proposal checklist covers everything you need for storm jobs.",
      "## Why Storm Jobs Need Special Proposals",
      "A standard roofing contractor proposal won't cut it for storm damage work. You're not just selling to the homeowner—you're documenting for the insurance company too.",
      "Storm proposals need to:",
      "- Match the insurance adjuster's line items",
      "- Include supplement language for hidden damage",
      "- Document existing conditions before work begins",
      "- Protect your payment when insurance drags their feet",
      "## The Storm Damage Contractor Proposal Checklist",
      "### Section 1: Documentation",
      "- Photos of all visible damage (before repair)",
      "- Insurance claim number",
      "- Adjuster name and contact info",
      "- Date of loss (storm date)",
      "- Copy of insurance estimate attached",
      "### Section 2: Scope of Work",
      "Your scope should mirror the insurance estimate categories:",
      "- **Tear-off**: Number of layers, squares, disposal",
      "- **Decking**: Replacement allowance and per-sheet pricing",
      "- **Drip edge**: Linear feet, material type",
      "- **Underlayment**: Synthetic or felt, ice and water locations",
      "- **Shingles**: Brand, style, color, warranty level",
      "- **Flashing**: Step, counter, pipe boots, valleys",
      "- **Ridge**: Venting, cap shingles, linear feet",
      "- **Cleanup**: Magnetic sweep, debris removal, dump fees",
      "### Section 3: Insurance-Specific Language",
      "Include these critical clauses:",
      "**Supplement Clause**: 'If additional damage is discovered during tear-off that was not visible during initial inspection, Contractor will document and submit a supplement claim to insurance. Homeowner agrees to sign supplement authorization within 48 hours of submission.'",
      "**Code Upgrade Clause**: 'If local building codes require upgrades beyond what insurance covers, Contractor will notify Homeowner of additional costs before proceeding.'",
      "**Payment Assignment**: 'Homeowner hereby assigns all insurance benefits for roofing work to Contractor to the extent of the contract amount.'",
      "### Section 4: Payment Terms",
      "Storm jobs need special payment structure:",
      "- **Deductible due at signing**: Homeowner's deductible paid upfront",
      "- **Insurance proceeds**: Paid directly to contractor or upon receipt",
      "- **Supplement payments**: Due within 7 days of insurance payment",
      "- **Depreciation recovery**: Due upon receipt from insurance",
      "Never start work without the deductible in hand.",
      "### Section 5: Timeline Considerations",
      "Storm season creates urgency, but protect yourself:",
      "- **Material availability**: Note that storm demand may affect material delivery times",
      "- **Permit timing**: Some municipalities are backlogged after major storms",
      "- **Crew scheduling**: First-come-first-served based on signed contracts and deposits",
      "### Section 6: Hidden Damage Protocol",
      "Spell out exactly what happens when you find more damage:",
      "1. Stop work and document with photos",
      "2. Notify homeowner within 24 hours",
      "3. Submit supplement to insurance",
      "4. Wait for approval before proceeding (or get homeowner authorization to proceed at their risk)",
      "5. Additional work invoiced separately",
      "## Sample Storm Damage Scope Items",
      "Here's how to write line items that match insurance estimates:",
      "- 'Remove existing roofing - 24 squares (2 layers) - $XX per square'",
      "- 'Dispose of roofing debris - 24 squares - $XX per square'",
      "- 'Replace damaged decking - up to 2 sheets included, additional at $85/sheet'",
      "- 'Install GAF Timberline HDZ - 24 squares - $XX per square'",
      "- 'Install synthetic underlayment - 24 squares - $XX per square'",
      "- 'Install ice and water shield at eaves - 72 LF - $XX per LF'",
      "- 'Replace drip edge - 180 LF - $XX per LF'",
      "- 'Replace pipe jacks - 6 each - $XX each'",
      "Using unit pricing makes supplements easier to document and approve.",
      "## Protect Your Payment",
      "Storm jobs have payment risks that regular jobs don't:",
      "- Insurance companies delay payment",
      "- Homeowners spend their insurance check on other things",
      "- Depreciation recoverable gets 'lost'",
      "Protect yourself with clear contractor proposal language:",
      "- 'Final payment due within 5 business days of insurance payment receipt'",
      "- 'Homeowner agrees to forward all insurance payments within 48 hours of receipt'",
      "- 'Contractor may file lien if payment not received within 30 days of project completion'",
      "## Generate Storm-Ready Contractor Proposals Fast",
      "Storm season moves fast. You don't have time to write proposals from scratch while leads are calling. [ScopeGen](/) generates professional roofing contractor proposals with all the insurance language, supplement clauses, and documentation you need.",
      "Generate your next proposal in 60 seconds with [ScopeGen](/)."
    ]
  },
  "why-homeowners-dont-understand-proposals": {
    slug: "why-homeowners-dont-understand-proposals",
    title: "Why Homeowners Don't Understand Your Proposal (and How to Fix It)",
    excerpt: "Your proposal makes perfect sense to you. But homeowners see jargon, confusion, and reasons to keep shopping. Here's how to write proposals they actually understand.",
    author: "ScopeGen Team",
    date: "December 11, 2025",
    readTime: "5 min read",
    category: "Business Tips",
    metaTitle: "Why Homeowners Don't Understand Your Proposal | ScopeGen",
    metaDescription: "Learn why homeowners get confused by contractor proposals and how to write clear proposals that win jobs. Simple fixes that increase your close rate.",
    content: [
      "You send a detailed contractor proposal. Radio silence. Or worse: 'We're going to get a few more bids.' The problem isn't your price—it's that homeowners don't understand what they're buying.",
      "## The Curse of Knowledge",
      "You've been in the trades for years. Terms like 'rough-in,' 'backer board,' and 'trim out' are second nature. But to a homeowner, your contractor proposal might as well be written in another language.",
      "When homeowners don't understand your proposal, they:",
      "- Focus only on the bottom-line price",
      "- Can't see why you cost more than the other guy",
      "- Delay making a decision (death for your sales process)",
      "- Default to whoever seems 'simplest'",
      "## Common Proposal Mistakes That Confuse Homeowners",
      "### Mistake 1: Too Much Jargon",
      "**Instead of**: 'Install 1/2\" HardieBacker on shower walls with thinset'",
      "**Write**: 'Install waterproof cement board behind your shower tile (this prevents water damage and mold)'",
      "Add a brief 'why' after technical items. Homeowners don't know why cement board matters—but 'prevents mold' makes sense instantly.",
      "### Mistake 2: Giant Walls of Text",
      "Your contractor proposal isn't a novel. Break up long paragraphs into:",
      "- Bullet points for scope items",
      "- Headers for each section",
      "- White space so it doesn't feel overwhelming",
      "Homeowners scan proposals. Make the important stuff easy to find.",
      "### Mistake 3: Hiding the Price",
      "Don't bury your price on page 4. Homeowners are looking for the number. If they can't find it easily, they get frustrated.",
      "Put your total investment prominently displayed. Break down the costs clearly so they see where the money goes.",
      "### Mistake 4: No Visual Hierarchy",
      "A contractor proposal that's all the same font size and style is hard to navigate. Use:",
      "- **Bold headers** for main sections",
      "- Larger font for section titles",
      "- Consistent formatting throughout",
      "Your proposal should have a clear visual flow: Project overview → Scope → Materials → Pricing → Terms.",
      "### Mistake 5: Missing the 'What's In It For Me'",
      "Homeowners don't care about your process—they care about their outcome. Connect your work to their benefits:",
      "- 'New exhaust fan' → 'New exhaust fan (eliminates mirror fog and prevents mold)'",
      "- 'GFCI outlets' → 'Safety outlets that prevent electrical shock in wet areas'",
      "- '2-coat paint system' → 'Premium 2-coat finish that lasts 10+ years'",
      "## Quick Fixes for Clearer Contractor Proposals",
      "### Fix 1: Add a Project Summary",
      "Start with a 2-3 sentence overview: 'This proposal covers a complete bathroom remodel including new tile shower, vanity, toilet, and flooring. Work will take approximately 10 business days. Your total investment is $18,500.'",
      "Now they know exactly what they're getting before reading details.",
      "### Fix 2: Group Work by Phase",
      "Instead of a random list of tasks, organize by logical phases:",
      "- **Week 1**: Demolition and rough plumbing",
      "- **Week 2**: Tile and fixture installation",
      "- **Week 3**: Finishing touches and cleanup",
      "This helps homeowners visualize the process.",
      "### Fix 3: Include a 'What's Not Included' Section",
      "Being clear about exclusions actually builds trust. It shows you've thought through the project completely and aren't hiding surprise charges.",
      "### Fix 4: End with Clear Next Steps",
      "Don't leave homeowners wondering what to do. End with: 'To move forward, simply sign below and return with your deposit. We'll contact you within 48 hours to schedule your start date.'",
      "## The Contractor Proposal That Wins",
      "The best contractor proposals aren't the longest or most technical. They're the clearest. Homeowners choose contractors they understand and trust.",
      "When your proposal is easy to read, explains the value, and shows clear next steps, you'll close more jobs—often at higher prices than your competitors.",
      "## Make Every Proposal Crystal Clear",
      "[ScopeGen](/) generates contractor proposals designed for homeowners, not other contractors. Clear language, logical organization, and professional formatting that builds trust.",
      "Generate your next proposal in 60 seconds with [ScopeGen](/)."
    ]
  },
  "starting-home-services-business": {
    slug: "starting-home-services-business",
    title: "Starting a Home Services Business: Challenges and Pitfalls to Avoid",
    excerpt: "Thinking about starting your own contracting or home services business? Learn the real challenges most new contractors face and how to avoid common mistakes.",
    author: "ScopeGen Team",
    date: "December 12, 2025",
    readTime: "8 min read",
    category: "Business Tips",
    metaTitle: "Starting a Home Services Business: Challenges & Pitfalls | ScopeGen",
    metaDescription: "Essential guide for starting a home services or contracting business. Learn common pitfalls, licensing requirements, and how to set yourself up for success.",
    content: [
      "Starting a home services business sounds simple: you're good at your trade, so why not work for yourself? But the reality hits hard. Most new contracting businesses fail within the first two years—not because the owners lack skills, but because they underestimate the business side.",
      "## The Dream vs. Reality",
      "The dream: Be your own boss. Set your own hours. Keep all the profit.",
      "The reality: You're now the salesperson, bookkeeper, scheduler, customer service rep, and tradesperson—all in one. And that 'profit' disappears fast when you forget to account for taxes, insurance, and slow seasons.",
      "Understanding these challenges upfront gives you a massive advantage over contractors who learn the hard way.",
      "## Challenge 1: Underpricing Your Work",
      "This is the #1 killer of new home services businesses. You price jobs the way you did as an employee—hourly rate times hours worked—and wonder why you're broke.",
      "### What You're Forgetting",
      "- **Taxes**: Self-employment tax is 15.3% on top of income tax",
      "- **Insurance**: General liability, vehicle, tools, workers comp",
      "- **Unbillable time**: Estimates, travel, admin, callbacks",
      "- **Materials markup**: You should mark up materials 20-50%",
      "- **Slow seasons**: You need reserves for when the phone stops ringing",
      "- **Retirement**: Nobody's matching your 401k anymore",
      "### The Fix",
      "Calculate your true hourly cost—including all overhead—then add your profit margin. Most successful contractors charge 2-3x what they'd earn as an employee. Use a contractor proposal that clearly shows the value you're delivering.",
      "## Challenge 2: No Systems for Estimates and Proposals",
      "In the beginning, you scribble prices on the back of a business card. It works... until it doesn't.",
      "### The Problems",
      "- You forget what you quoted and lose money",
      "- Homeowners compare your napkin to a competitor's professional contractor proposal",
      "- You can't remember what was included when disputes arise",
      "- You waste hours rewriting the same scope of work",
      "### The Fix",
      "Create systems from day one. Use contractor proposal software to generate professional estimates quickly. Every job should have a written scope of work, even small ones. This protects you legally and makes you look established.",
      "## Challenge 3: Licensing and Insurance Gaps",
      "Many new contractors start working before they're properly licensed and insured. This is a ticking time bomb.",
      "### What You Need",
      "- **Business license**: Required in most jurisdictions",
      "- **Contractor license**: Required for most trades over certain dollar amounts",
      "- **General liability insurance**: Protects you if you damage a client's property",
      "- **Workers compensation**: Required if you have employees in most states",
      "- **Vehicle insurance**: Commercial coverage for work vehicles",
      "- **Bonding**: Required for some trades and some states",
      "### The Consequences of Skipping",
      "- Fines and penalties if caught working unlicensed",
      "- No legal recourse if a client doesn't pay",
      "- Personal liability for any damages or injuries",
      "- Inability to pull permits (which educated homeowners notice)",
      "Get licensed and insured before you take your first job. The cost is worth the protection and credibility.",
      "## Challenge 4: Feast or Famine Cash Flow",
      "New contractors often go from 'more work than I can handle' to 'where did everyone go?' overnight. Without cash reserves, one slow month can sink your business.",
      "### Why This Happens",
      "- You stop marketing when you're busy",
      "- Seasonal fluctuations (especially in roofing, HVAC, landscaping)",
      "- Economic downturns hit home services first",
      "- Large projects end, and the pipeline is empty",
      "### The Fix",
      "- Keep marketing even when busy—leads take time to convert",
      "- Save 3-6 months of expenses before leaving your job",
      "- Diversify services if possible (maintenance contracts, smaller jobs)",
      "- Get deposits upfront to fund materials and labor",
      "## Challenge 5: Trying to Do Everything Yourself",
      "You started this business for freedom, but now you're working 70-hour weeks handling every task yourself.",
      "### The Trap",
      "- You're the best at your trade, so you do all the work",
      "- You can't afford help, so you do your own bookkeeping",
      "- You don't trust anyone, so you handle every call",
      "### The Fix",
      "Start delegating or automating early:",
      "- Use accounting software (QuickBooks, Wave) instead of spreadsheets",
      "- Use contractor proposal software instead of writing everything from scratch",
      "- Hire a part-time helper before you're drowning",
      "- Consider a virtual assistant for scheduling and follow-ups",
      "Your time has a value. If you can earn $75/hour doing your trade, don't spend hours on $15/hour tasks.",
      "## Challenge 6: Not Getting Paid",
      "You did the work, but the check never comes. Without proper contracts and payment terms, you have limited options.",
      "### Common Payment Problems",
      "- No written agreement, so it's your word against theirs",
      "- No deposit, so you're funding their project",
      "- Final payment 'pending' indefinitely",
      "- Disputes over what was included in the price",
      "### The Fix",
      "Every job needs a written contractor proposal that includes:",
      "- Detailed scope of work",
      "- Clear payment schedule with deposits",
      "- What happens if payment is late",
      "- Your right to file a mechanic's lien",
      "Never start work without a signed agreement and deposit.",
      "## Challenge 7: No Reputation Yet",
      "Established contractors have reviews, referrals, and a track record. You're starting from zero.",
      "### Building Credibility Fast",
      "- Ask every satisfied customer for a Google review",
      "- Take before/after photos of every job",
      "- Create a simple website with your work and contact info",
      "- Present professional contractor proposals (this alone sets you apart)",
      "- Join local business groups and trade associations",
      "- Consider small jobs for friends at cost to build your portfolio",
      "Your first 20 jobs are about building reputation as much as making money.",
      "## The Path Forward",
      "Starting a home services business is challenging, but thousands of contractors do it successfully every year. The ones who make it:",
      "- Price their work properly from day one",
      "- Use systems and software to stay organized",
      "- Get licensed, insured, and bonded",
      "- Maintain cash reserves for slow periods",
      "- Present professional contractor proposals that win trust",
      "- Build their reputation intentionally",
      "## Tools That Help You Look Established",
      "One of the fastest ways to compete with established contractors is to look as professional as they do. [ScopeGen](/) helps new contractors create polished contractor proposals that rival companies ten times their size.",
      "Generate your next proposal in 60 seconds with [ScopeGen](/)."
    ]
  },
  "electrician-pricing-strategies": {
    slug: "electrician-pricing-strategies",
    title: "Electrician Pricing Strategies: How to Price Your Services Profitably",
    excerpt: "Master electrician pricing with proven strategies for service calls, panel upgrades, and new construction. Stop leaving money on the table.",
    author: "ScopeGen Team",
    date: "December 12, 2025",
    readTime: "9 min read",
    category: "Pricing",
    metaTitle: "Electrician Pricing Strategies: How to Price Electrical Work | ScopeGen",
    metaDescription: "Complete guide to electrician pricing strategies. Learn how to price service calls, panel upgrades, rewires, and new construction work profitably.",
    content: [
      "Pricing electrical work is part science, part art. Charge too little and you're working for free. Charge too much and the phone stops ringing. This guide covers proven pricing strategies that help electricians stay profitable while winning jobs.",
      "## The Electrician's Pricing Dilemma",
      "Electrical work is invisible to most homeowners. They see the light switch work, not the hours of wire pulling, code compliance, and safety testing behind it. This makes pricing tricky—you're selling expertise and safety, not just 'a new outlet.'",
      "Your contractor proposal needs to communicate value, not just list prices.",
      "## Understanding Your True Costs",
      "Before setting any prices, you need to know exactly what it costs you to operate. Most electricians drastically underestimate their overhead.",
      "### Direct Costs (Per Job)",
      "- **Materials**: Wire, boxes, breakers, fixtures, connectors",
      "- **Permits**: Electrical permits for major work",
      "- **Labor**: Your time or employee wages",
      "- **Vehicle**: Fuel and mileage for the job",
      "### Overhead Costs (Monthly)",
      "- **Insurance**: General liability ($1,500-3,000/year), vehicle, tools",
      "- **Licensing**: State license fees, continuing education",
      "- **Vehicle**: Payment, insurance, maintenance",
      "- **Tools**: Replacement and calibration",
      "- **Software**: Accounting, scheduling, contractor proposal software",
      "- **Phone/Internet**: Business lines",
      "- **Marketing**: Website, ads, business cards",
      "- **Taxes**: Self-employment (15.3%) plus income tax",
      "Add up your monthly overhead and divide by billable hours. This is your 'cost to exist' per hour before you've made any profit.",
      "## Pricing Method 1: Hourly Rate",
      "Charging by the hour is simple but risky. It punishes efficiency—the faster you work, the less you earn.",
      "### How to Calculate Your Hourly Rate",
      "1. Determine your target annual income (e.g., $80,000)",
      "2. Add annual overhead costs (e.g., $30,000)",
      "3. Total needed: $110,000",
      "4. Divide by billable hours (1,500-1,800 per year is realistic)",
      "5. $110,000 ÷ 1,600 = $69/hour minimum",
      "6. Add profit margin (20-30%): $85-90/hour",
      "### When Hourly Works",
      "- Troubleshooting and diagnostics",
      "- Time-and-materials service calls",
      "- When you genuinely can't estimate scope",
      "### When Hourly Fails",
      "- Jobs you can complete quickly (you lose money)",
      "- When homeowners fixate on 'hours worked'",
      "- Larger projects where flat-rate is expected",
      "## Pricing Method 2: Flat Rate / Project Pricing",
      "Flat-rate pricing quotes a single price for a defined scope of work. You make more money when you work efficiently.",
      "### How to Build Flat Rates",
      "For common jobs, track your actual time and materials over several installations:",
      "- **Outlet installation**: Average 45 minutes + $15 materials = $185-225",
      "- **Ceiling fan install (existing box)**: 1 hour + $0-50 materials = $150-200",
      "- **Panel upgrade (100A to 200A)**: 6-8 hours + $800-1,200 materials = $2,500-4,500",
      "Build a price book for your most common services. Your contractor proposal can then quote consistent prices quickly.",
      "### Advantages of Flat Rate",
      "- Rewards efficiency",
      "- Homeowners prefer knowing the price upfront",
      "- Easier to quote and close jobs",
      "- Builds a systematic, scalable business",
      "## Pricing by Job Type",
      "### Service Calls and Troubleshooting",
      "Most electricians charge a service call fee ($75-150) that covers showing up and basic diagnosis. This fee typically applies to the first hour or converts to labor if you do the work.",
      "**Pricing approach:**",
      "- Service call fee: $85-125",
      "- Hourly rate for additional time: $85-125/hour",
      "- Or flat-rate the repair once diagnosed",
      "### Outlet and Switch Work",
      "Simple outlet and switch work is often priced flat-rate:",
      "- **New outlet (existing circuit)**: $175-275",
      "- **New outlet (new circuit)**: $350-500",
      "- **GFCI outlet**: $150-250",
      "- **Dimmer switch**: $100-175",
      "- **Smart switch**: $125-200 + device cost",
      "### Panel Upgrades",
      "Panel upgrades vary significantly based on scope:",
      "- **100A to 200A upgrade**: $2,000-4,500",
      "- **Panel replacement (same amperage)**: $1,500-2,500",
      "- **Subpanel installation**: $800-2,000",
      "- **Meter/panel combo replacement**: $2,500-5,000",
      "Always include permit costs in your contractor proposal—educated homeowners expect permitted work.",
      "### Whole-House Rewire",
      "Rewiring is typically priced per square foot or by the circuit:",
      "- **Per square foot**: $8-15 (varies by access and complexity)",
      "- **Per circuit**: $200-350 (including home run)",
      "- **Typical 2,000 sq ft home**: $12,000-25,000",
      "### EV Charger Installation",
      "EV chargers are a growing market with predictable pricing:",
      "- **Level 2 charger install (existing capacity)**: $400-800",
      "- **Level 2 with new circuit (panel has space)**: $800-1,500",
      "- **Level 2 requiring panel upgrade**: $3,000-5,000",
      "### New Construction",
      "New construction is typically priced per square foot:",
      "- **Basic spec home**: $4-6 per sq ft",
      "- **Custom home**: $6-10 per sq ft",
      "- **High-end/smart home**: $10-15+ per sq ft",
      "For new construction, your contractor proposal should detail exactly what's included: number of circuits, outlet count, fixture allowances, and smart home rough-ins.",
      "## Markup on Materials",
      "Many electricians forget to mark up materials. You're providing procurement, delivery, and warranty backup. Standard markup is 20-50% on materials.",
      "**Example:**",
      "- 200A panel cost: $400",
      "- Your price: $500-600",
      "- Breakers at cost: $15 each",
      "- Your price: $20-25 each",
      "This isn't gouging—it's covering your time picking up materials, warranty handling, and inventory management.",
      "## Presenting Your Prices",
      "How you present prices matters as much as the prices themselves. A professional contractor proposal builds confidence that justifies your rates.",
      "### What Your Proposal Should Include",
      "- **Scope of work**: Every task in detail",
      "- **Materials list**: What you're installing (brand, quality)",
      "- **Code compliance**: Note that work meets current electrical code",
      "- **Permit status**: Whether permit is included",
      "- **Warranty**: Your workmanship guarantee",
      "- **Timeline**: When you'll complete the work",
      "### Avoid Price-Only Quotes",
      "'Panel upgrade: $3,500' tells homeowners nothing. They'll compare it to a $2,800 quote that excludes permits and uses inferior materials.",
      "Instead, detail what they're getting: 'Install new 200-amp Siemens panel with 40-space/40-circuit capacity, including new meter socket, grounding system upgrade, whole-house surge protection, and all permits and inspections.'",
      "## Handling Price Objections",
      "When homeowners push back on price, don't immediately discount. Instead:",
      "1. **Understand the objection**: Is it truly budget, or lack of perceived value?",
      "2. **Reinforce value**: Licensed, insured, permitted, warranty, code-compliant",
      "3. **Offer options**: Maybe they don't need the whole-house surge protector today",
      "4. **Stand firm on fair pricing**: Lowball bids attract lowball clients",
      "Remember: the cheapest electrician in town isn't the most successful one. The most professional, reliable one is.",
      "## Build Your Price Book with ScopeGen",
      "[ScopeGen](/) helps electricians create professional contractor proposals with consistent pricing. Enter your rates once, and generate detailed proposals in about a minute. No more scribbling prices on invoices.",
      "Generate your next proposal in 60 seconds with [ScopeGen](/)."
    ]
  }
};

export const blogSlugs = Object.keys(blogPosts);

export default function BlogIndex() {
  useEffect(() => {
    document.title = "Contractor Blog | Proposal Tips & Business Advice | ScopeGen";
    const metaDesc = document.querySelector('meta[name="description"]');
    if (metaDesc) {
      metaDesc.setAttribute("content", "Free resources for contractors: proposal writing tips, pricing guides, scope of work templates, and business advice to help you win more jobs.");
    }
  }, []);

  const posts = Object.values(blogPosts).sort((a, b) => 
    new Date(b.date).getTime() - new Date(a.date).getTime()
  );

  return (
    <Layout>
      <section className="bg-gradient-to-br from-slate-900 via-slate-800 to-slate-900 text-white py-16">
        <div className="container mx-auto px-4">
          <div className="max-w-3xl mx-auto text-center">
            <h1 className="text-4xl md:text-5xl font-display font-bold mb-4" data-testid="blog-title">
              Contractor Resources
            </h1>
            <p className="text-xl text-slate-300">
              Proposal tips, pricing guides, and business advice to help you win more jobs.
            </p>
          </div>
        </div>
      </section>

      <section className="py-16 bg-white">
        <div className="container mx-auto px-4">
          <div className="max-w-4xl mx-auto">
            <div className="space-y-8">
              {posts.map((post) => (
                <article key={post.slug} className="border-b border-slate-200 pb-8" data-testid={`blog-post-${post.slug}`}>
                  <Link href={`/blog/${post.slug}`}>
                    <div className="group cursor-pointer">
                      <div className="flex items-center gap-4 text-sm text-slate-500 mb-3">
                        <span className="bg-orange-100 text-orange-700 px-3 py-1 rounded-full">
                          {post.category}
                        </span>
                        <span className="flex items-center gap-1">
                          <Calendar className="h-4 w-4" />
                          {post.date}
                        </span>
                        <span className="flex items-center gap-1">
                          <Clock className="h-4 w-4" />
                          {post.readTime}
                        </span>
                      </div>
                      <h2 className="text-2xl font-bold text-slate-900 group-hover:text-orange-600 transition-colors mb-3">
                        {post.title}
                      </h2>
                      <p className="text-slate-600 mb-4">{post.excerpt}</p>
                      <span className="inline-flex items-center text-orange-600 font-medium group-hover:gap-2 transition-all">
                        Read more <ArrowRight className="h-4 w-4 ml-1" />
                      </span>
                    </div>
                  </Link>
                </article>
              ))}
            </div>
          </div>
        </div>
      </section>

      <section className="py-16 bg-slate-50">
        <div className="container mx-auto px-4">
          <div className="max-w-3xl mx-auto text-center">
            <h2 className="text-3xl font-display font-bold mb-4">Ready to Create Better Proposals?</h2>
            <p className="text-lg text-slate-600 mb-8">
              Stop writing proposals from scratch. Use our trade-specific templates to create professional proposals in minutes.
            </p>
            <Link href="/app">
              <Button size="lg" className="bg-orange-500 hover:bg-orange-600 text-white gap-2" data-testid="blog-cta">
                Try ScopeGen Free <ArrowRight className="h-5 w-5" />
              </Button>
            </Link>
          </div>
        </div>
      </section>
    </Layout>
  );
}
