"use client";

import * as React from "react";
import Image from "next/image";
import Link from "next/link";
import { ArrowRight } from "lucide-react";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { cn } from "@/lib/utils";

// Proposal data types
interface LineItem {
  description: string;
  amount: number;
}

interface ProposalData {
  id: string;
  title: string;
  type: string;
  imageSrc: string;
  imageAlt: string;
  lineItems: LineItem[];
  subtotal: number;
  tax: number;
  total: number;
}

// Sample proposal data
const proposals: ProposalData[] = [
  {
    id: "bathroom",
    title: "Bathroom Remodel",
    type: "Sample",
    imageSrc: "/images/scopescan/projects/bathroom-real.jpg",
    imageAlt: "Real bathroom remodel job site photo",
    lineItems: [
      { description: "Demo existing tub/shower and vanity", amount: 850 },
      { description: "Install new tub/shower surround", amount: 2800 },
      { description: "New vanity + top + faucet", amount: 1650 },
      { description: "Replace toilet (standard)", amount: 650 },
      { description: "Tile floor replacement (up to 50 sqft)", amount: 2500 },
    ],
    subtotal: 8450,
    tax: 0,
    total: 8450,
  },
  {
    id: "roofing",
    title: "Roof Replacement",
    type: "Sample",
    imageSrc: "/images/examples/roof-jobsite.jpg",
    imageAlt: "Roof replacement job site photo",
    lineItems: [
      { description: "Tear off shingles + underlayment", amount: 2400 },
      { description: "Replace damaged decking (allowance)", amount: 1200 },
      { description: "Synthetic underlayment + ice/water shield", amount: 1850 },
      { description: "Install architectural shingles", amount: 6200 },
      { description: "Replace flashing + pipe boots", amount: 1330 },
    ],
    subtotal: 12980,
    tax: 0,
    total: 12980,
  },
];

// Format currency
function formatCurrency(amount: number): string {
  return new Intl.NumberFormat("en-US", {
    style: "currency",
    currency: "USD",
    minimumFractionDigits: 0,
    maximumFractionDigits: 0,
  }).format(amount);
}

// Mini Proposal Preview (HTML document style)
function ProposalPreview({
  proposal,
  compact = false,
}: {
  proposal: ProposalData;
  compact?: boolean;
}) {
  return (
    <div
      className={cn(
        "bg-white border border-slate-200 rounded-lg shadow-sm overflow-hidden",
        compact ? "text-sm" : ""
      )}
    >
      {/* Header */}
      <div className="bg-slate-900 px-4 py-3">
        <div className="flex items-center justify-between">
          <div>
            <h4 className="text-white font-semibold text-sm">
              {proposal.title}
            </h4>
            <p className="text-slate-400 text-xs mt-0.5">Proposal #{proposal.id.toUpperCase()}-2025</p>
          </div>
          <span className="text-xs bg-orange-500 text-white px-2 py-1 rounded font-medium">
            {proposal.type}
          </span>
        </div>
      </div>

      {/* Line Items */}
      <div className={cn("px-4", compact ? "py-3" : "py-4")}>
        <div className="space-y-2">
          {proposal.lineItems.map((item, idx) => (
            <div
              key={idx}
              className="flex justify-between items-start gap-4 text-slate-700"
            >
              <span className={cn("flex-1", compact ? "text-xs" : "text-sm")}>
                {item.description}
              </span>
              <span
                className={cn(
                  "font-medium tabular-nums flex-shrink-0",
                  compact ? "text-xs" : "text-sm"
                )}
              >
                {formatCurrency(item.amount)}
              </span>
            </div>
          ))}
        </div>

        {/* Totals */}
        <div
          className={cn(
            "border-t border-slate-200 mt-4 pt-3 space-y-1.5",
            compact ? "text-xs" : "text-sm"
          )}
        >
          <div className="flex justify-between text-slate-600">
            <span>Subtotal</span>
            <span className="tabular-nums">{formatCurrency(proposal.subtotal)}</span>
          </div>
          <div className="flex justify-between text-slate-600">
            <span>Tax</span>
            <span className="tabular-nums">{formatCurrency(proposal.tax)}</span>
          </div>
          <div className="flex justify-between font-bold text-slate-900 pt-1 border-t border-slate-100">
            <span>Total</span>
            <span className="tabular-nums">{formatCurrency(proposal.total)}</span>
          </div>
        </div>
      </div>

      {/* Footer */}
      <div className="bg-slate-50 px-4 py-2 border-t border-slate-100">
        <p className="text-[10px] text-slate-400 text-center">
          Generated by ScopeGen
        </p>
      </div>
    </div>
  );
}

// Full Proposal Modal Content
function FullProposalView({ proposal }: { proposal: ProposalData }) {
  return (
    <div className="bg-white rounded-lg overflow-hidden">
      {/* Header */}
      <div className="bg-slate-900 px-6 py-5">
        <div className="flex items-center justify-between">
          <div>
            <h3 className="text-white font-bold text-xl">{proposal.title}</h3>
            <p className="text-slate-400 text-sm mt-1">
              Proposal #{proposal.id.toUpperCase()}-2025 • December 31, 2025
            </p>
          </div>
          <div className="text-right">
            <span className="text-xs bg-orange-500 text-white px-3 py-1.5 rounded-full font-semibold">
              Sample Proposal
            </span>
          </div>
        </div>
      </div>

      {/* Project Info */}
      <div className="grid sm:grid-cols-2 gap-4 p-6 bg-slate-50 border-b border-slate-200">
        <div>
          <h4 className="text-xs font-semibold text-slate-500 uppercase tracking-wide mb-1">
            Project Location
          </h4>
          <p className="text-slate-900 font-medium">123 Main Street</p>
          <p className="text-slate-600 text-sm">Anytown, USA 12345</p>
        </div>
        <div>
          <h4 className="text-xs font-semibold text-slate-500 uppercase tracking-wide mb-1">
            Prepared For
          </h4>
          <p className="text-slate-900 font-medium">Sample Customer</p>
          <p className="text-slate-600 text-sm">sample@email.com</p>
        </div>
      </div>

      {/* Line Items */}
      <div className="p-6">
        <h4 className="text-sm font-semibold text-slate-900 mb-4 uppercase tracking-wide">
          Scope of Work
        </h4>
        <div className="space-y-3">
          {proposal.lineItems.map((item, idx) => (
            <div
              key={idx}
              className="flex justify-between items-start gap-4 py-2 border-b border-slate-100 last:border-0"
            >
              <div className="flex items-start gap-3">
                <span className="flex-shrink-0 w-6 h-6 bg-slate-100 rounded-full flex items-center justify-center text-xs font-medium text-slate-600">
                  {idx + 1}
                </span>
                <span className="text-slate-700">{item.description}</span>
              </div>
              <span className="font-semibold text-slate-900 tabular-nums flex-shrink-0">
                {formatCurrency(item.amount)}
              </span>
            </div>
          ))}
        </div>

        {/* Totals */}
        <div className="border-t-2 border-slate-200 mt-6 pt-4 space-y-2">
          <div className="flex justify-between text-slate-600">
            <span>Subtotal</span>
            <span className="tabular-nums font-medium">
              {formatCurrency(proposal.subtotal)}
            </span>
          </div>
          <div className="flex justify-between text-slate-600">
            <span>Tax</span>
            <span className="tabular-nums font-medium">
              {formatCurrency(proposal.tax)}
            </span>
          </div>
          <div className="flex justify-between text-xl font-bold text-slate-900 pt-2 border-t border-slate-200">
            <span>Total</span>
            <span className="tabular-nums">{formatCurrency(proposal.total)}</span>
          </div>
        </div>
      </div>

      {/* Footer */}
      <div className="bg-slate-50 px-6 py-4 border-t border-slate-200">
        <div className="flex items-center justify-between">
          <p className="text-xs text-slate-500">
            Generated by ScopeGen • Professional contractor proposals
          </p>
          <div className="flex items-center gap-2">
            <span className="w-2 h-2 bg-green-500 rounded-full"></span>
            <span className="text-xs text-slate-600">Ready to send</span>
          </div>
        </div>
      </div>
    </div>
  );
}

// Proposal Card Component
function ProposalCard({ proposal }: { proposal: ProposalData }) {
  const [modalOpen, setModalOpen] = React.useState(false);
  const [imageError, setImageError] = React.useState(false);

  return (
    <>
      <div className="bg-white rounded-xl border border-slate-200 shadow-sm overflow-hidden hover:shadow-md transition-shadow">
        {/* Job Photo */}
        <div className="relative aspect-[16/10] bg-slate-100">
          {imageError ? (
            <div className="absolute inset-0 bg-gradient-to-br from-slate-200 to-slate-300 flex items-center justify-center">
              <span className="text-slate-500 text-sm">Job Photo</span>
            </div>
          ) : (
            <Image
              src={proposal.imageSrc}
              alt={proposal.imageAlt}
              fill
              sizes="(max-width: 768px) 100vw, 50vw"
              className="object-cover"
              onError={() => setImageError(true)}
            />
          )}
        </div>

        {/* Proposal Preview */}
        <div className="p-4">
          <ProposalPreview proposal={proposal} compact />
        </div>

        {/* Actions */}
        <div className="px-4 pb-4 flex flex-col sm:flex-row gap-3">
          <button
            onClick={() => setModalOpen(true)}
            className="flex-1 inline-flex items-center justify-center h-10 px-4 rounded-lg border border-slate-300 bg-white text-slate-700 font-medium text-sm hover:bg-slate-50 hover:border-slate-400 transition-colors"
          >
            View full sample
          </button>
          <Link
            href="/app"
            className="flex-1 inline-flex items-center justify-center h-10 px-4 rounded-lg bg-orange-500 text-white font-semibold text-sm hover:bg-orange-600 transition-colors shadow-sm"
          >
            Start Generating
            <ArrowRight className="ml-1.5 w-4 h-4" />
          </Link>
        </div>
      </div>

      {/* Modal */}
      <Dialog open={modalOpen} onOpenChange={setModalOpen}>
        <DialogContent className="max-w-2xl p-0 overflow-hidden [&>button]:bg-white/90 [&>button]:rounded-full [&>button]:p-2 [&>button]:shadow-md [&>button]:hover:bg-white [&>button]:opacity-100">
          <DialogHeader className="sr-only">
            <DialogTitle>{proposal.title} - Full Sample</DialogTitle>
          </DialogHeader>
          <FullProposalView proposal={proposal} />
        </DialogContent>
      </Dialog>
    </>
  );
}

// Main Section Component
export function ProposalPreviewSection() {
  return (
    <section
      id="demo"
      className="py-16 sm:py-20 bg-slate-50 border-t border-slate-100"
      data-testid="section-proposal-samples"
    >
      <div className="container mx-auto px-4">
        <div className="max-w-6xl mx-auto">
          {/* Header */}
          <div className="text-center mb-12">
            <h2 className="text-3xl sm:text-4xl md:text-5xl font-heading font-bold text-slate-900 mb-4">
              See the proposal your customer will receive
            </h2>
            <p className="text-slate-600 text-lg sm:text-xl max-w-2xl mx-auto">
              Clean scope, clear pricing, and a format built to close faster.
            </p>
          </div>

          {/* Proposal Cards Grid */}
          <div className="grid md:grid-cols-2 gap-6 lg:gap-8">
            {proposals.map((proposal) => (
              <ProposalCard key={proposal.id} proposal={proposal} />
            ))}
          </div>

          {/* Bottom CTA */}
          <div className="mt-12 text-center">
            <p className="text-slate-500 text-sm mb-4">
              Ready to send professional proposals in minutes?
            </p>
            <Link
              href="/app"
              className="inline-flex items-center justify-center h-12 px-8 rounded-lg bg-slate-900 text-white font-bold text-base hover:bg-slate-800 transition-colors shadow-md"
            >
              Create Your First Proposal Free
              <ArrowRight className="ml-2 w-5 h-5" />
            </Link>
          </div>
        </div>
      </div>
    </section>
  );
}
